package avutil

//#cgo pkg-config: libavutil
//#include <libavutil/channel_layout.h>
import "C"

const (
 AV_CH_LAYOUT_MONO              =C.AV_CH_LAYOUT_MONO
 AV_CH_LAYOUT_STEREO            =C.AV_CH_LAYOUT_STEREO
 AV_CH_LAYOUT_2POINT1           =C.AV_CH_LAYOUT_2POINT1
 AV_CH_LAYOUT_2_1               =C.AV_CH_LAYOUT_2_1
 AV_CH_LAYOUT_SURROUND          =C.AV_CH_LAYOUT_SURROUND
 AV_CH_LAYOUT_3POINT1           =C.AV_CH_LAYOUT_3POINT1
 AV_CH_LAYOUT_4POINT0           =C.AV_CH_LAYOUT_4POINT0
 AV_CH_LAYOUT_4POINT1           =C.AV_CH_LAYOUT_4POINT1
 AV_CH_LAYOUT_2_2               =C.AV_CH_LAYOUT_2_2
 AV_CH_LAYOUT_QUAD              =C.AV_CH_LAYOUT_QUAD
 AV_CH_LAYOUT_5POINT0           =C.AV_CH_LAYOUT_5POINT0
 AV_CH_LAYOUT_5POINT1           =C.AV_CH_LAYOUT_5POINT1
 AV_CH_LAYOUT_5POINT0_BACK      =C.AV_CH_LAYOUT_5POINT0_BACK
 AV_CH_LAYOUT_5POINT1_BACK      =C.AV_CH_LAYOUT_5POINT1_BACK
 AV_CH_LAYOUT_6POINT0           =C.AV_CH_LAYOUT_6POINT0
 AV_CH_LAYOUT_6POINT0_FRONT     =C.AV_CH_LAYOUT_6POINT0_FRONT
 AV_CH_LAYOUT_HEXAGONAL         =C.AV_CH_LAYOUT_HEXAGONAL
 AV_CH_LAYOUT_6POINT1           =C.AV_CH_LAYOUT_6POINT1
 AV_CH_LAYOUT_6POINT1_BACK      =C.AV_CH_LAYOUT_6POINT1_BACK
 AV_CH_LAYOUT_6POINT1_FRONT     =C.AV_CH_LAYOUT_6POINT1_FRONT
 AV_CH_LAYOUT_7POINT0           =C.AV_CH_LAYOUT_7POINT0
 AV_CH_LAYOUT_7POINT0_FRONT     =C.AV_CH_LAYOUT_7POINT0_FRONT
 AV_CH_LAYOUT_7POINT1           =C.AV_CH_LAYOUT_7POINT1
 AV_CH_LAYOUT_7POINT1_WIDE      =C.AV_CH_LAYOUT_7POINT1_WIDE
 AV_CH_LAYOUT_7POINT1_WIDE_BACK =C.AV_CH_LAYOUT_7POINT1_WIDE_BACK
 AV_CH_LAYOUT_OCTAGONAL         =C.AV_CH_LAYOUT_OCTAGONAL
 AV_CH_LAYOUT_HEXADECAGONAL     =C.AV_CH_LAYOUT_HEXADECAGONAL
 AV_CH_LAYOUT_STEREO_DOWNMIX    =C.AV_CH_LAYOUT_STEREO_DOWNMIX
 AV_CH_LAYOUT_22POINT2          =C.AV_CH_LAYOUT_22POINT2
)

func AvGetChannelLayoutNbChannels(channelLayout int) int {
	return int(C.av_get_channel_layout_nb_channels(C.uint64_t(channelLayout)))
}
